export const Style = {
  Navbar: {
    backgroundColor: "transparent",
    position: "absolute",
    top: 0,
    right: 0,
    left: 0,
    zIndex: 9,
    paddingTop: "20px",
    paddingBottom: "20px",
  },
  Navbar_toggler: {
    border: "0",
    padding: "0",
    cursor: "pointer",
    margin: "0",
    width: "30px",
    height: "35px",
    outline: "none",
  },
  navbar_toggler_icon: {
    background: "var(--white-color)",
    display: "block",
    width: "30px",
    height: "2px",
    position: "relative",
  },
  Span1: {
    position: "absolute",
    right: 0,
    left: 0,
    background: "var(--white-color)",
    width: "30px",
    height: "2px",
    content: "''",
    top: "-8px",
  },
  Span2: {
    position: "absolute",
    right: 0,
    left: 0,
    background: "var(--white-color)",
    width: "30px",
    height: "2px",
    content: "''",
    top: "8px",
  },
  Dropdown_item: {
    display: "inline-block",
    color: "var(--p-bg-color)",
    fontFamily: "var(--title-font-family)",
    fontSize: "var(--menu-font-size)",
    fontWeight: "var(--font-weight-medium)",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    position: "relative",
  },
  Custom_btn: {
    appearance: "none",
    backgroundColor: "transparent",
    border: "2px solid var(--white-color)",
    borderRadius: "var(--border-radius-large)",
    color: "var(--white-color)",
    fontFamily: "var(--title-font-family)",
    fontSize: "var(--p-font-size)",
    fontWeight: "var(--font-weight-semibold)",
    lineHeight: "normal",
    transition: "all 300ms cubic-bezier(0.23, 1, 0.32, 1)",
    padding: "10px 20px",
    cursor: "pointer",
    userSelect: "none",
    touchAction: "manipulation",
  },
};
