export const genres = [
  { value: 1, name: "Action" },
  { value: 2, name: "Adventure" },
  { value: 5, name: "Avant Garde" },
  { value: 46, name: "Award Winning" },
  { value: 28, name: "Boys Love" },
  { value: 4, name: "Comedy" },
  { value: 8, name: "Drama" },
  { value: 10, name: "Fantasy" },
  { value: 26, name: "Girls Love" },
  { value: 47, name: "Gourmet" },
  { value: 14, name: "Horror" },
  { value: 7, name: "Mystery" },
  { value: 22, name: "Romance" },
  { value: 24, name: "Sci-Fi" },
  { value: 36, name: "Slice of Life" },
  { value: 30, name: "Sports" },
  { value: 37, name: "Supernatural" },
  { value: 41, name: "Suspense" },
  { value: 9, name: "Ecchi" },
  { value: 49, name: "Erotica" },
  { value: 12, name: "Hentai" },
  { value: 50, name: "Adult Cast" },
  { value: 51, name: "Anthropomorphic" },
  { value: 52, name: "CGDCT" },
  { value: 53, name: "Childcare" },
  { value: 54, name: "Combat Sports" },
  { value: 81, name: "Crossdressing" },
  { value: 55, name: "Delinquents" },
  { value: 39, name: "Detective" },
  { value: 56, name: "Educational" },
  { value: 57, name: "Gag Humor" },
  { value: 58, name: "Gore" },
  { value: 35, name: "Harem" },
  { value: 59, name: "High Stakes Game" },
  { value: 13, name: "Historical" },
  { value: 60, name: "Idols (Female)" },
  { value: 61, name: "Idols (Male)" },
  { value: 62, name: "Isekai" },
  { value: 63, name: "Josei" },
  { value: 64, name: "Kids" },
  { value: 65, name: "Magic" },
  { value: 66, name: "Martial Arts" },
  { value: 67, name: "Mecha" },
  { value: 68, name: "Military" },
  { value: 69, name: "Music" },
  { value: 70, name: "Mystery" },
  { value: 71, name: "Psychological" },
  { value: 72, name: "Samurai" },
  { value: 73, name: "School" },
  { value: 74, name: "Seinen" },
  { value: 75, name: "Shoujo" },
  { value: 76, name: "Shoujo Ai" },
  { value: 77, name: "Shounen" },
  { value: 78, name: "Shounen Ai" },
  { value: 79, name: "Space" },
  { value: 80, name: "Sports" },
  { value: 82, name: "Super Power" },
  { value: 83, name: "Thriller" },
  { value: 84, name: "Vampire" },
  { value: 85, name: "Yaoi" },
  { value: 86, name: "Yuri" },
];
